version: "3"
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        
    app:
        image: vrashuk/app:test
        build: 
            context: "."
            dockerfile: Dockerfile
        command: bash -c "sleep 3 && npm start"

        environment:
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}

        depends_on:
            - db

volumes:
    pgdata: