name: push

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_NAME: vrashuk/app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up docker build
        uses: docker/setup-buildx-action@v2

      - name: Run test
        run: make cp-env ci

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push build to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest